# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    curl -fsSL https://git.io/shellspec | sh -s -- --yes
  displayName: 'Install Shellspec'

- script: echo "Deploy"
  displayName: 'Terraform Deploy'

- script: |
    shellspec
  displayName: 'Run Tests'
  workingDirectory: spec
