# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: Install Shellspec
  inputs:
    azureSubscription: 'hashobok'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      curl -fsSL https://git.io/shellspec | sh -s -- --yes


- script: |
    terraform init
    terraform plan -out=plan.tfplan
    terraform apply "plan.tfplan"

  workingDirectory: terraform
  displayName: 'Terraform Deploy'

- task: AzureCLI@2
  displayName: Run Infrastructure Tests
  inputs:
    workingDirectory: test
    azureSubscription: 'hashobok'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      shellspec -f d
      shellspec -f j > tests.xml

- task: PublishTestResults@2
  continueOnError: true
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/tests.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/test'
    testRunTitle: 'Infrastructure Tests'